#主页面
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *

class Ui_MainWindow(object):
    stop=0
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1120, 700)
        MainWindow.setStyleSheet("#frame{border-image: url(:/sign/BUPT.png);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame_5)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.pushButton = QtWidgets.QPushButton(self.frame_3)
        self.pushButton.setObjectName("pushButton")
        #self.pushButton.setFlat(True)
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout_4.addWidget(self.frame_3)

        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(10)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.student_informations_9 = QtWidgets.QFrame(self.frame_4)
        self.student_informations_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.student_informations_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.student_informations_9.setObjectName("student_informations_9")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.student_informations_9)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(10)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.student_informations_9)
        self.label_2.setObjectName("label_2")
        pixmap = QPixmap('C:/Users/DELL/PycharmProjects/aiprogram/face/renxiang.jpg')
        self.label_2.setPixmap(pixmap)
        self.label_2.setScaledContents(True)
        self.horizontalLayout_5.addWidget(self.label_2)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setSpacing(10)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_62 = QtWidgets.QLabel(self.student_informations_9)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.verticalLayout_42.addWidget(self.label_62)
        self.label_63 = QtWidgets.QLabel(self.student_informations_9)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_42.addWidget(self.label_63)
        self.label_64 = QtWidgets.QLabel(self.student_informations_9)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.label_64.setFont(font)
        self.label_64.setObjectName("label_64")
        self.verticalLayout_42.addWidget(self.label_64)
        self.horizontalLayout_29.addLayout(self.verticalLayout_42)
        self.verticalLayout_43 = QtWidgets.QVBoxLayout()
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.name_9 = QtWidgets.QLabel(self.student_informations_9)
        self.name_9.setText("")
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.name_9.setFont(font)
        self.name_9.setObjectName("name_9")
        self.verticalLayout_43.addWidget(self.name_9)
        self.xuehao_9 = QtWidgets.QLabel(self.student_informations_9)
        self.xuehao_9.setText("")
        font = QtGui.QFont()
        font.setFamily("song")
        font.setPointSize(24)
        self.xuehao_9.setFont(font)
        self.xuehao_9.setObjectName("xuehao_9")
        self.verticalLayout_43.addWidget(self.xuehao_9)
        self.class_10 = QtWidgets.QLabel(self.student_informations_9)
        self.class_10.setText("")
        font = QtGui.QFont()
        font.setFamily("song")
        font.setPointSize(24)
        self.class_10.setFont(font)
        self.class_10.setObjectName("class_10")
        self.verticalLayout_43.addWidget(self.class_10)
        self.horizontalLayout_29.addLayout(self.verticalLayout_43)
        self.horizontalLayout_29.setStretch(0, 39)
        self.horizontalLayout_29.setStretch(1, 109)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_29)
        self.horizontalLayout_5.setStretch(0, 96)
        self.horizontalLayout_5.setStretch(1, 204)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addWidget(self.student_informations_9)

        self.sign_in_result_9 = QtWidgets.QLabel(self.frame_4)
        self.sign_in_result_9.setObjectName("sign_in_result_9")
        self.verticalLayout_3.addWidget(self.sign_in_result_9)
        pixmap = QPixmap('C:/Users/DELL/PycharmProjects/aiprogram/face/dd.jpg')
        self.sign_in_result_9.setPixmap(pixmap)
        self.sign_in_result_9.setScaledContents(True)
        self.frame_23 = QtWidgets.QFrame(self.frame_4)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_23)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")

        self.label_65 = QtWidgets.QLabel(self.frame_23)
        self.label_65.setObjectName("label_65")
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.label_65.setFont(font)
        self.horizontalLayout_30.addWidget(self.label_65)
        self.sign_1_num_9 = QtWidgets.QLabel(self.frame_23)
        self.sign_1_num_9.setText("")
        font = QtGui.QFont()
        font.setFamily("song")
        font.setPointSize(24)
        self.sign_1_num_9.setFont(font)
        self.sign_1_num_9.setObjectName("sign_1_num_9")
        self.horizontalLayout_30.addWidget(self.sign_1_num_9)
        self.label_66 = QtWidgets.QLabel(self.frame_23)
        self.label_66.setObjectName("label_66")
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        self.label_66.setFont(font)
        self.horizontalLayout_30.addWidget(self.label_66)
        self.sign_0_num_9 = QtWidgets.QLabel(self.frame_23)
        self.sign_0_num_9.setText("")
        font = QtGui.QFont()
        font.setFamily("song")
        font.setPointSize(24)
        self.sign_0_num_9.setFont(font)
        self.sign_0_num_9.setObjectName("sign_0_num_9")
        self.horizontalLayout_30.addWidget(self.sign_0_num_9)
        self.verticalLayout_3.addWidget(self.frame_23)
        self.verticalLayout_3.setStretch(0, 141)
        self.verticalLayout_3.setStretch(1, 41)
        self.verticalLayout_3.setStretch(2, 41)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4.addWidget(self.frame_4)
        self.horizontalLayout_4.setStretch(0, 71)
        self.horizontalLayout_4.setStretch(1, 131)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_67 = QtWidgets.QLabel(self.frame_5)
        self.label_67.setObjectName("label_67")
        font = QtGui.QFont()
        font.setFamily("song")
        font.setPointSize(20)
        self.label_67.setFont(font)
        self.horizontalLayout_2.addWidget(self.label_67)
        self.class_name_8 = QtWidgets.QLabel(self.frame_5)
        self.class_name_8.setText("")
        self.class_name_8.setObjectName("class_name_8")
        self.horizontalLayout_2.addWidget(self.class_name_8)
        self.label_68 = QtWidgets.QLabel(self.frame_5)
        self.label_68.setObjectName("label_68")
        self.horizontalLayout_2.addWidget(self.label_68)
        self.time_8 = QtWidgets.QLabel(self.frame_5)
        self.time_8.setText("")
        font = QtGui.QFont()
        font.setFamily("song")
        font.setPointSize(22)
        self.time_8.setFont(font)
        self.time_8.setObjectName("time_8")
        self.horizontalLayout_2.addWidget(self.time_8)
        self.label_69 = QtWidgets.QLabel(self.frame_5)
        self.label_69.setObjectName("label_69")
        font = QtGui.QFont()
        font.setFamily("song")
        font.setPointSize(22)
        self.label_69.setFont(font)
        self.horizontalLayout_2.addWidget(self.label_69)
        self.horizontalLayout_2.setStretch(0, 91)
        self.horizontalLayout_2.setStretch(1, 121)
        self.horizontalLayout_2.setStretch(2, 111)
        self.horizontalLayout_2.setStretch(3, 41)
        self.horizontalLayout_2.setStretch(4, 41)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 7)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_4.addWidget(self.frame_5)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 717, 29))
        self.menubar.setObjectName("menubar")
        self.menuhelps = QtWidgets.QMenu(self.menubar)
        self.menuhelps.setObjectName("menuhelps")
        self.menusettings = QtWidgets.QMenu(self.menubar)
        self.menusettings.setObjectName("menusettings")
        self.menu_K = QtWidgets.QMenu(self.menubar)
        self.menu_K.setObjectName("menu_K")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actioninformations = QtWidgets.QAction(MainWindow)
        self.actioninformations.setObjectName("actioninformations")
        self.actionaddress_name = QtWidgets.QAction(MainWindow)
        self.actionaddress_name.setObjectName("actionaddress_name")
        self.actionconfidence = QtWidgets.QAction(MainWindow)
        self.actionconfidence.setObjectName("actionconfidence")
        self.action_Y = QtWidgets.QAction(MainWindow)
        self.action_Y.setObjectName("action_Y")
        self.menuhelps.addAction(self.actioninformations)
        self.menusettings.addAction(self.actionaddress_name)
        self.menusettings.addAction(self.actionconfidence)
        self.menu_K.addAction(self.action_Y)
        self.menubar.addAction(self.menuhelps.menuAction())
        self.menubar.addAction(self.menu_K.menuAction())
        self.menubar.addAction(self.menusettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "智能校园签到系统"))
        self.pushButton.setText(_translate("MainWindow", "TAKE"))
        self.label_2.setText(_translate("MainWindow", ""))
        self.label_62.setText(_translate("MainWindow", "        姓名："))
        self.label_63.setText(_translate("MainWindow", "        学号："))
        self.label_64.setText(_translate("MainWindow", "        班级："))
        self.label_65.setText(_translate("MainWindow", "已签到人数："))
        self.label_66.setText(_translate("MainWindow", "  未签到人数："))
        self.label_67.setText(_translate("MainWindow", "当前课程名称：  程序设计实验"))
        self.label_68.setText("<font color=%s>%s</font>" %('#EAFF82', "         距离课程开始还有："))
        self.label_69.setText("<font color=%s>%s</font>" %('#D5FF30', "分钟！"))
        self.menuhelps.setTitle(_translate("MainWindow", "文件(&F)"))
        self.menusettings.setTitle(_translate("MainWindow", "设置(&M)"))
        self.menu_K.setTitle(_translate("MainWindow", "查看(&K)"))
        self.actioninformations.setText(_translate("MainWindow", "添加(&A)"))
        self.actionaddress_name.setText(_translate("MainWindow", "重置(&R)"))
        self.actionconfidence.setText(_translate("MainWindow", "活体检测(&H)"))
        self.action_Y.setText(_translate("MainWindow", "签到日志(&S)"))
